### ISSUE TITLE
Add reference to V1

### ISSUE THREAD

**Issue by sabre1041** [redhat-cop/uncontained.io#105]
As content is migrated from v1.uncontained.io, add a reference to denote the location of older material (some that may not be ultimately migrated)

**Comment by rdebeasi** [comment]
What's the reason for keeping older material around? What sort of content wouldn't be migrated to the new site?

When we set up v1, I had assumed that we'd decommission it when the new site launched and redirect v1 to the new site. I think it would be confusing to have the same content in two different places. This duplication also means that we wouldn't have one "canonical" location for a page, which is [bad for SEO](https://moz.com/blog/rel-canonical).

I'd propose the following:
- If there's content or functionality from v1 that we need on uncontained.io, let's move those elements over.
- If there's content on v1 that doesn't make sense on the new site, let's find a new home for it.
- Once everything from v1 has made it to uncontained.io, shut down v1 and redirect its content to the corresponding pages on uncontained.io.

Does that sound reasonable?

**Comment by sabre1041** [comment]
@rdebeasi The primary reason is to support content that no longer fits into the scope of the uncontained.io site and is better served hosted by another property (KCS in CEE for example). 

I would rather take the time going through the material now so we can address it prior to migrating and then potentially letting the task drop off of the radar. 

I foresee v1 lasting for some time until the assets are hosted on new properties

@etsauer input?

**Comment by rdebeasi** [comment]
Gotcha - thanks for clearing that up. I'm cool with that as long as we can migrate and redirect everything that _does_ fit into the scope of uncontained.io.
