### ISSUE TITLE
Establish a theme and intent for the site.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#106]
This issue will serve as a collaboration space to work out a better communication of the theme and intent of uncontained. Once established we will:

- Update the About page
- Update our content model readme

**Comment by rdebeasi** [comment]
To start with, here's the statement on our homepage:
 
>## On containers, cloud, and digital transformation.
>
>We are a community of experts passionate about open source emerging technologies at play in the digital transformation journey. Our aim is to provide valuable community resources to IT Organizations attempting to adopt open source and cloud technologies with an intent towards DevOps or lean methodologies.

Here are some notes from March of last year (see [this doc](https://docs.google.com/document/d/1OuixiAls5cVZjz5tQFCspmo8Oye2vYU_c3BwWVZJ98Q/edit#heading=h.9y3rf4gidg6v)):

> ## Goals of the Space
>
>* To make technical “tribal knowledge” more accessible for Red Hat associates, partners and customers
>* Promote the thought leadership of Red Hat Services and Communities of Practice
>* Promote our open source ideals by taking external contributions and inviting other organizations to join the effort
> * Establish good practices in emerging technologies where there aren’t any currently
>
> ## What is Out of Scope for this Project?
>
>- Product Documentation
>- Blog Posts
>- “Tips & Tricks” type short form documents
>
> ## Audience
>
> - Red Hatters in the Field (Consultants, SAs, etc.)
> - Red Hat Partners
> - Red Hat Customers & Potential Customers

**Comment by JaredBurck** [comment]
v2 uncontained.io was launched at NA RHTE in 2019.  Closing issue as completed for v2.
stale - will not fix
