### ISSUE TITLE
Fix internal links

### ISSUE THREAD

**Issue by rdebeasi** [redhat-cop/uncontained.io#11]
Some links from one document to another currently 404. For example, `/articles/openshift-custom-certificates/` links to "Installing a Hightly Available OpenShift Cluster" at `/playbooks/installation/` instead of `/guides/openshift-ha-installation/`.

The migration script could handle this: when an article/guide is migrated, the script could update any references to that document from any other content. On the other hand, an unexpected, global find-and-replace sounds risky; maybe it would be better to fix links manually and add a note to the contributing guide stating that the user do a search-and-replace to update links after migrating a document.

**Comment by etsauer** [comment]
@rdebeasi can we close this?

**Comment by JaredBurck** [comment]
Eric confirmed can be closed
