### ISSUE TITLE
New Article: Containerized x509 for OpenShift Authentication

### ISSUE THREAD

**Issue by chrisruffalo** [redhat-cop/uncontained.io#110]
Useful mainly for public sector contributors who need x509 (CAC/PIV) authentication for OpenShift.

Existing documentation covers this topic broadly but here we have a solution that works in less time and uses OpenShift features to get working more quickly.

Topics:
- Adding an x509 Proxy Container to OpenShift
- Configuring relevant OpenShift resources
- Customizing Proxy for local needs
- Optional: Working with LDAP Sync

For more information: https://github.com/RedHatOfficial/ose-pivproxy

**Comment by etsauer** [comment]
@redhat-cop/content-coalition @sferich888

**Comment by chrisruffalo** [comment]
@etsauer ping

**Comment by sferich888** [comment]
This needs to be synced with https://bugzilla.redhat.com/show_bug.cgi?id=1314526 (likely to close the RFE) as something consulting can offer. 

As you can see from the description we in Support have a solution (but its really just a workaround).

**Comment by chrisruffalo** [comment]
The UI in recent versions of OpenShift lets you get your token to log into
the `oc` command. I feel like that but has been OBE. Getting x509 to work
from the oc client would be much more involved. Especially since all the
x509 method does is redirect to the SSL Proxy, return, and give your
browser the identity token.

**Comment by JaredBurck** [comment]
still needs someone to write content to be reviewed and published
