### ISSUE TITLE
New Article: Fluentd Log Forwarding via Containers

### ISSUE THREAD

**Issue by chrisruffalo** [redhat-cop/uncontained.io#111]
Useful for OpenShift clusters that do not want to use non-cluster resources (other VMs) as an intermediary to forwarding Fluentd traffic outside of the cluster.

Old guide on Fluentd Forwarding doesn't appear to have been included in this version of uncontained.io. The containerized version allows the traffic to never leave the cluster and does not require non-cluster resources.

Topics:
- Pros and cons of in-cluster forwarding
- Adding and configuring fluentd forwarding
  - For Splunk
  - For Remote Syslog
- Customizing fluentd forwarding
- Creating filters and indexes
- Optional: scaling log forwarding (Replicas or DaemonSets)

See: https://github.com/CDCgov/openshift-fluentd-forwarder

**Comment by etsauer** [comment]
@redhat-cop/content-coalition @sferich888 this sounds like something that should exist in a KB. In the "old site", we have these two docs: 

1. http://v1.uncontained.io/playbooks/operationalizing/secure-forward-splunk.html
2. http://v1.uncontained.io/playbooks/operationalizing/secure-forward-splunk-container.html

Two questions:

1. Should these guides be converted to KCS articles/solutions?
2. @chrisruffalo are you looking for something that's not coverted in the second linke above?

**Comment by etsauer** [comment]
@sferich888 ^

**Comment by sferich888** [comment]
I don't understand the need for this the product includes this functionality: 

https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#sending-logs-to-an-external-elasticsearch-instance and https://docs.openshift.com/container-platform/3.11/install_config/aggregate_logging.html#fluentd-external-log-aggregator document this. 

What you all seem to be pointing out is a specific implementation example (for Splunk)? Is that correct? 
If so this would make a good KCS candidate.

**Comment by sferich888** [comment]
This also needs to close out https://bugzilla.redhat.com/show_bug.cgi?id=1510276

**Comment by chrisruffalo** [comment]
This solution is an implementation of the above that then forwards to a
third party integration. The documentation only covers a remote fluentd or
a remote Elastic Search instance.

Right now the articles extend support for Splunk and, I believe, Remote
Syslog. They could build support for other sinks too. Or the product could
be RFE’d to include more forwarders.

**Comment by chrisruffalo** [comment]
I see it supports remote syslog out of the box now.
