### ISSUE TITLE
New Article: Cloud provider integrations

### ISSUE THREAD

**Issue by David-Igou** [redhat-cop/uncontained.io#115]
Why this would be valuable: Anybody who has done Openshift deployments on a cloud platform knows and understands each service has their own unique set of quirks/caveats. This is especially true for a field setting due to integrations with another organizations infrastructure - branching out of scope of the official Openshift documentation.

There are some subsections in the installation guide that make references to AWS (Most are `TODO`), but I feel that in the bigger picture this warrants its own separate article, due to the number of providers that can be covered all having their own sections and thus quickly gaining length

I'm aware that we have repositories containing scripts that, provided a key and some unique identifier will create your infrastructure. But, that is not in the spirit of educating users of requirements for OCP to operate on these platforms 

For example, here's a potential layout:

* Amazon Web Services
  * Dynamic Provisioning of infrastructure
  * Route53 
  * Security groups
  * Requirements for cloud plugin
    * NodeName
    * IAM Roles
  * Known Issues
* Azure
  * Dynamic Provisioning of infrastructure
  * Known Issues
    * Cloudprovider plugin failing to initialize
    * Dynamic storage latency
* Google Compute Engine
  * Dynamic Provisioning of infrastructure
  * Known Issues
* Openstack
  * Dynamic Provisioning of infrastructure
  * Known Issues

My knowledge lacks on GCE/OpenStack deployments, but you get the picture - All of these have "gotcha's" that can give people trouble in the field, and doing lab builds can be expensive if funded personally.

Feedback/suggestions are welcome

**Comment by JaredBurck** [comment]
still needs someone to write content to be reviewed and published
