### ISSUE TITLE
Enable Travis to test Pull Requests

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#129]
@sabre1041 @JaredBurck @mwitzenm just noticed this in the last few PRs.

**Comment by sabre1041** [comment]
@etsauer just checked and it was not enabled in travis. it has been reenabled

**Comment by etsauer** [comment]
@sabre1041 it actually looks like we've never turned them on before. I thought we had, but there is no build history. Perhaps i'm misremembering. I've turned them off again for now, but will keep this issue open with the goal of getting travis builds working for this repo.

**Comment by etsauer** [comment]
https://github.com/redhat-cop/openshift-applier/blob/master/.travis.yml

**Comment by etsauer** [comment]
This has been resolved by #162
