### ISSUE TITLE
Remove unused dependancies

### ISSUE THREAD

**Issue by Digi59404** [redhat-cop/uncontained.io#132]
Noticed a bunch of dependancies loading on the master branch. This took a while to install. I ran depcheck against the repo and found numerous dependancies that are unused and have dependency trees of their own that are unused.

We should remove any unused dependancies.

`MacBook-Pro:uncontained.io digi$ depcheck
Unused dependencies
* bootstrap
* css-loader
* exports-loader
* file-loader
* imports-loader
* jquery
* minimatch
* popper.js
* postcss-cssnext
* postcss-import
* url-loader
* whatwg-fetch
Unused devDependencies
* eslint
Missing dependencies
* babel-eslint
* chalk
* humanize-duration`

**Comment by etsauer** [comment]
@Digi59404 can we close this?

**Comment by Digi59404** [comment]
Absolutely. Your recent merge resolved it! Thanks!
