### ISSUE TITLE
Add depcheck to the CI/CD Pipeline

### ISSUE THREAD

**Issue by Digi59404** [redhat-cop/uncontained.io#133]
We should add depcheck to the CI/CD pipeline to audit our packages. Ensuring that we're not including bad packages and we're not missing any dependancies causing random exceptions.

https://www.npmjs.com/package/depcheck

**Comment by etsauer** [comment]
@Digi59404 can we close this?

**Comment by Digi59404** [comment]
Absolutely. Your recent merge resolved it!
