### ISSUE TITLE
Load Balancer Guide is out of date.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#140]
Our load balancing guide is grossly out of date. It makes recommendations that we no longer thing is a good idea. Need to put some effort into a refresh.

http://uncontained.io/articles/openshift-load-balancing/

**Comment by huddlesj** [comment]
Will update doc according to the following doc after testing.

https://clouddocs.f5.com/containers/v2/openshift/

**Comment by etsauer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update load balancer guide to instruct on how to use named_certificates as the preferred method](https://trello.com/c/NRnNECB7/111-update-load-balancer-guide-to-instruct-on-how-to-use-namedcertificates-as-the-preferred-method)
