### ISSUE TITLE
Upgrade to Asciidoctor 2.x

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#145]
A new version of asciidoctor has been released (v2.x). If I rebuild our local-dev image we get a bunch of errors like this on build:

```
ERROR 2019/03/25 17:52:12 articles/openshift-and-the-org.adoc: /usr/local/bundle/gems/asciidoctor-2.0.1/lib/asciidoctor/reader.rb:591:in `rescue in prepare_lines': asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - source is either binary or contains invalid Unicode data (ArgumentError)
```

I think this may be related to https://github.com/asciidoctor/asciidoctor/issues/2884, but not yet sure what the fix is.

**Comment by dobozysaurus** [comment]
FYI, I upgraded to asciidoctor 2.0.10 and ran both gulp build and gulp test locally, and it worked just fine for me. Is that sufficient to test this issue, or do you only get it when running through docker?

**Comment by etsauer** [comment]
@dobozysaurus hmm, it looks like that issue I had referenced has since closed, so perhaps it has been fixed! If you'd like to contribute a resolution for this, please open a PR setting our standard asciidoctor version to 2.x.

**Comment by etsauer** [comment]
@dobozysaurus to ensure your fix will work, I would recommend running through our test suite locally. https://github.com/redhat-cop/uncontained.io/blob/master/CONTRIBUTING.adoc#running-the-automated-tests

**Comment by dobozysaurus** [comment]
Cool - ran the test suite locally, and everything checked out. PR is here: https://github.com/redhat-cop/uncontained.io/pull/173.
