### ISSUE TITLE
Article: Best Practices - OpenShift Log lifecycle

### ISSUE THREAD

**Issue by jimdillon** [redhat-cop/uncontained.io#156]
I have quite a few customers ask for best practices around log lifecycles for OCP clusters.  We can point to enterprise standards, but we should also have an approach to fall back on if that standard does not exist.

**Comment by etsauer** [comment]
@bbeaudoin @huddlesj @lpsantil @JaredBurck FYI.

@jimdillon can you provide some more specific context or guidance around what you are looking for?

**Comment by JaredBurck** [comment]
still needs someone to write content to be reviewed and published
