### ISSUE TITLE
F5 docs and references should be updated.

### ISSUE THREAD

**Issue by huddlesj** [redhat-cop/uncontained.io#157]
Updated instructions have changed for F5 integration. Docs ( http://uncontained.io/articles/openshift-load-balancing/ ) should be updated to reference the new F5 plugin ( https://docs.openshift.com/container-platform/3.11/install_config/router/f5_router.html )

**Comment by etsauer** [comment]
@huddlesj I think what you mean is this: https://clouddocs.f5.com/containers/v2/openshift/

**Comment by etsauer** [comment]
related to #140

**Comment by huddlesj** [comment]
This is another difference I have found If you look at the 3.10 docs they point to the f5 site but if you look at the 3.11 docs the instructions are back on the Red Hat docs site

3.10: https://docs.openshift.com/container-platform/3.10/install_config/router/f5_router.html
3.11: https://docs.openshift.com/container-platform/3.11/architecture/networking/assembly_available_router_plugins.html

**Comment by huddlesj** [comment]
@etsauer Ok, I see it now -> The F5 router plug-in will be deprecated in OpenShift Container Platform version 3.11. The functionality of the F5 router plug-in is replaced in the F5 BIG-IP® Controller for OpenShift. 

https://docs.openshift.com/container-platform/3.11/install_config/router/f5_router.html

**Comment by etsauer** [comment]
@huddlesj please move all of this info over to #140 and close this issue.

**Comment by huddlesj** [comment]
Duplicate of issue #140
