### ISSUE TITLE
New Article: Describe a process by which an App team could work on application onboarding without a cluster

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#167]
We see often enough in the field that some organizations are slow to start onboarding to a container platform due to traditional infrastructure environments, and provisioning slowness. In this case, application teams get frustrated because they are ready to work, but don't have a target environment to deploy to.

We should write a guide that walks through some patterns for local development of containers, including the use of minishift/code ready containers, minikube, s2i, podman etc. on a local workstation.

**Comment by JaredBurck** [comment]
still needs someone to write content to be reviewed and published
