### ISSUE TITLE
[New Article] CoreOS MatchBox Overview.

### ISSUE THREAD

**Issue by Jooho** [redhat-cop/uncontained.io#169]
CoreOS MatchBox help network boot and provision CoreOS clusters that fit for OpenShift 4. 

For OCP4 baremetal UPI installation, official openshift installer repo provides matchbox example and terraform match provider help configure matchbox easier.

From this new article, I want to explain matchbox itself and how to config it using terraform with example.

**Comment by Jooho** [comment]
Why the topic is broadly useful to uncontained.io contributors
~~~
For OCP4 baremetal UPI installation, official openshift installer repo provides matchbox example and terraform match provider help configure matchbox easier. 
~~~

Why it doesn’t fit into an existing guide
~~~
Official openshift 4 documentation only explains a manual way for bare metal installation. However, openshift installer repo provides terraform example of the Matchbox for bare metal installation without any explanation. Therefore, if we provide more information about matchbox, it would be great!
~~~

3-5 bullets of expected sub-topics
- What is matchbox?
- How does it work?
- Get started Matchbox
  - Install Matchbox
  - Config Matchbox using terraform provider
  - Find machine by mac or label

**Comment by JaredBurck** [comment]
still needs someone to review content and published
