### ISSUE TITLE
[New Article] Monitoring multiple Openshift Cluster using prometheus

### ISSUE THREAD

**Issue by AndreaFerraresi** [redhat-cop/uncontained.io#172]
Who would be interested?
Useful mainly for cloud providers that want to offer OpenShift clusters as a service, but still want to keep control on what is happening. Or for whoever has to operate more than a cluster at once. 

Why I did not contribute to anything existing? 
Couldn't find anything about this on the website, and I think can be beneficial 

What I will be writing about? 

- How to scale prometheus 
- Strategies to collect metrics and alerts into one or more central prometheus
- Prometheus push gateway vs prometheus federation 
- Prometheus in the cloud: different backends and their limitations

Hope this helps :)

**Comment by robbbbh** [comment]
I've been doing some work deploying a proof of poncept Thanos deployment recently for a customer. This could potentially be an interesting addition to this new article suggestion. It allows for multi cluster monitoring from one Thanos Query interface by connected different Prometheus metric stores together. (through both prometheus sidecars are block storage)

**Comment by AndreaFerraresi** [comment]
Yes, we could stick our heads together, do you want to send me an email about your idea?

**Comment by robbbbh** [comment]
Sure, I'll ping you and email this afternoon.

**Comment by AndreaFerraresi** [comment]
I think that this would be a very nice joint effort for an article, it would really cover the topic deeply. 

I would be in, but I guess requires other feedbacks.

**Comment by etsauer** [comment]
@robbbbh @AndreaFerraresi I think this is a great idea. I think we have others also working on this, so I'll try to bring some others to the table to collaborate.

**Comment by JaredBurck** [comment]
still needs someone to write content to be reviewed and published
