### ISSUE TITLE
Add https support

### ISSUE THREAD

**Issue by goldmann** [redhat-cop/uncontained.io#204]
It would be good to serve this site on https.

**Comment by jkeam** [comment]
For reference, you can see the current cert.

<img width="701" alt="wrong_cert" src="https://user-images.githubusercontent.com/48856/81343757-94377780-9083-11ea-83bb-41ca4618bea6.png">

**Comment by etsauer** [comment]
Agreed. unfortunately we can't use the provided cert for a top level domain, so we'll need to purchase one.
