### ISSUE TITLE
OpenShift powered blockchain reference use case application running on IBM Blockchain Platform deployed to IBM, AWS and MS AZURE clouds - as a reference implementation architecture

### ISSUE THREAD

**Issue by pvrbharg** [redhat-cop/uncontained.io#212]
**SUBJECT/TITLE**

OpenShift powered blockchain reference use case application running on IBM Blockchain Platform deployed to IBM, AWS and MS AZURE clouds - as a reference implementation architecture

**PURPOSE**

Highlight the power and value proposition of OpenShift CaaS versus vanilla IKS
Highlight the value of openness and non-vendor lock-in benefits - with OpenShift hosting
Highlight the value of Redhat Marketplace, Operator technologies for automation and non-vendor lockin
Reference implementation of a reference blockchain use case on a multi-cloud deployment topology with best practices
Highlight the value proposition of permissioned and commercial version of Hyperledger Fabric frameworks with IBM Blockchain Platform - again openness, non-vendor lock-in and other benefits of enterprise ready blockchain technologies.

**RELEVANCE**

Readers who are interested in OpenShift or Operators topics gravitate to uncontained.io resource and this is where this topic also belongs - since this is of interest to readers/developers/practitioners/customers/partners. This is a natural fit.

IBM Blockchain Platform service incidentally happens to run on OCP - another variation of a service with reference implementation. 

**TOPICS**

Why any one should care for permissioned blockchain technology
Why any one should care for Hyperledger Fabric and IBM Blockchain Platform with Linux Foundation
Why any one should care for Kubernetes and especially OCP version of Kubernetes or CaaS platform
Background on reference use case  and its design points
Reference implementation architecture
Resource requirements for solution deployment - IBM, AWS, MS AZURE clouds and OpenShift PaaS running on these CSPs
Role of Redhat Marketplace, Operators versus other vendor locked-in options - AWS and MS-AZURE market places
Validation and proof points of deployed solution working correctly - multi-cloud/hybrid-cloud solution deployment success

Lessons learnt and best practice recommendations.

Thanks.

**Comment by pvrbharg** [comment]
@jaredburck @etsauer  @sabre1041 @redhat-cop/cant-contain-this - Dear team - hope you are doing OK, keeping safe and socially distanced! I am and I am hoping you could give me a bit of your wisdom and guidance. Cheers!

**Comment by etsauer** [comment]
Hey @pvrbharg this sounds like an interesting and very ambitious article. We'd be happy to host that content in uncontained. Is this something that you yourself are interested in working on, or are you just requesting content for this need?

**Comment by pvrbharg** [comment]
Dear @etsauer Thank you and you inspire me even more! You already inspired me with your content that I benefited from!  Regarding your question:
>>> Is this something that you yourself are interested in working on
         My apologies - I am not being clear here!
          I have the work done and just write-up pending. This would be my thank you to you and community from which I 
          benefited and this is my giveback to uncontained.io and its committers/community.
          My other goal is to - share the success that I and my team experienced while also shining the advantages of Redhat 
          Marketplace, Automation [Operators and OLM] and the power of OpenShift [on AWS, IBM and MS AZURE cloud 
          platforms].

Given your blessing - I and my team would write a draft and share our work artifacts with you - for your review, feedback, guidance and final hosting. 

Regards.
