### ISSUE TITLE
Add site search

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#25]
Here some options for Hugo: https://gohugo.io/tools/search/

**Comment by rdebeasi** [comment]
Related #43

**Comment by rdebeasi** [comment]
The Open Practice Library (also built with Hugo) recently got this feature: https://github.com/rht-labs/practice-library

**Comment by etsauer** [comment]
@rdebeasi since the practice library is already demonstrating this capability, would it make sense to just go ahead and implement the same thing here rather than worry about #43 ?

**Comment by rdebeasi** [comment]
If someone's interested in picking this work up, sure! There is some work involved in integrating this work into our theme. We'd have to build a search results template and integrate the search index generation into our Gulp build. (Practice library is using Grunt but will eventually switch over to Gulp).

It's not a huge amount of work, but it's not trivial either. Knowing that, would you prefer to keep this in vNext or move it to MVP?

**Comment by huddlesj** [comment]
Would this be something simple to start with -> https://developers.google.com/custom-search/docs/tutorial/implementingsearchbox

**Comment by rdebeasi** [comment]
That's totally an option!

My preference would be for a search feature that's built into the site. That way, we don't have to wait for Google to update its index when the site changes and users get a more integrated experience. That said, we could definitely start with Google custom search and then move to rolling our own built-in search!

**Comment by etsauer** [comment]
This is done.
