### ISSUE TITLE
Set expectations on homepage

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#26]

**Comment by rdebeasi** [comment]
Consider a bar or something else unobtrusive on homepage.

**Comment by lwrigh** [comment]
@etsauer @rdebeasi Here is a rough first pass at a homepage wireframe: https://redhat.invisionapp.com/share/V2N37WHPSJ6 Feel free to click the link to see the wireframe and leave comments directly in Invision if you like. Any visuals, content, scale, or components you see are placeholders. Do you guys think any other particular type of content would be important to surface on the home page?

**Comment by etsauer** [comment]
@lwrigh sorry for taking so long to get back to you on this. Next time drop a bump, as i mostly forgot :).

I think these changes are great, and make a lof sense. Would you be able to open PRs with the changes to this piece-by-piece? For exmaple.. I think the Contribute section and Top page Nav we could merge in with very little discussion. 

Some of the other components probably merit some further discussion, but I like the direction.

One other thing that comes to mind here is that we do not currently have our style guide anywhere that's publicly accessible. Considering everything else is in the repo, we should probably look for some way to publish it as well, rather than storing it in Google Drive. Having that more accessible would help us have conversations around changes to style and color choices, such as an alternatve color for buttons and things. (I think we do need a non-blue alternate color, just want to make sure we are making a concious decision when we add things to our color palette). 

@rdebeasi @jimdillon @JaredBurck what do you think?

**Comment by lwrigh** [comment]
@etsauer Yup I can make PRs for the different sections of it i.e. navigation, body content, footer, etc. 

We can definitely talk more about the content and specific direction we want to go in. Different parts such as search and what articles vs. guides exactly mean might be good places to start off with. 

With regards to posting design deliverables such as the style guide or wireframes to more of a public place, teams that I've worked with in the past have used GitHub to keep track of design work and have conversations. We would post screenshots of the wireframes or keep the Invision document open and have conversations about the design work directly in the GitHub issue that it was associated with. It was a good way to keep a history of the design work.

**Comment by etsauer** [comment]
@lwrigh awesome. Yeah, we actually have a "style guide" readme in the repo already, but it really only addresses the content style, not the site style. Perhaps it could serve both functions. https://github.com/redhat-cop/uncontained.io/blob/master/docs/style_guide.md

**Comment by lwrigh** [comment]
@etsauer Nice that sounds like a good place to start storing all design related material. We can build it out and add content related to site style and other related bits along the way.

**Comment by etsauer** [comment]
@redhat-cop/cant-contain-this here is my first stab at our splash text:

```
Uncontained.io: On containers, cloud, and digital transformation.

We are a community of experts passionate about the part that open source technologies play in the digital transformation journey. Our aim is to provide valuable community resources to IT Organizations attempting to adopt open source & cloud technologies with an intent towards DevOps or lean methodologies.
```

**Comment by JaredBurck** [comment]
@etsauer I like it!  Made a couple changes in the tag line and 1st sentence.

```
uncontained.io:  containers, clouds, digital transformations and beyond

We are a community of experts passionate about open source emerging technologies
that play in the digital transformation journey. Our aim is to provide valuable 
community resources to IT Organizations attempting to adopt open source and 
cloud technologies with an intent towards DevOps or lean methodologies.
```
Thoughts?

**Comment by etsauer** [comment]
@JaredBurck what were the problems you were trying to correct with the top line? I don't think I agree with the pluralization of `cloud` and `digital transformation`, as they are concepts, not objects that can be enumerated. 

As far as the subtext paragraph, I would `s/that play/at play/` and I think we've got something.

**Comment by etsauer** [comment]
Closing this for now. we can reopen later if we think it needs updating.
