### ISSUE TITLE
Change styling of in-line code snippets to be more consistent with the site.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#33]

**Comment by rdebeasi** [comment]
This covers inline code, vs. code blocks (#34). It's hard to tell the difference between code and normal text. Check the style guide for the right treatment, then implement it.

**Comment by etsauer** [comment]
@rdebeasi so, the style guide, while it says "Inline Code", actually only covers code blocks. Inline code would be something `like this`, which we don't currently have any style guidance on. I've tried simply changing the font to match, but it doesn't seem quite enough to me.

Also, the font "Source Code Variable" doesn't seem to exist. Did we possibly mean [Source Code Pro](https://fonts.google.com/specimen/Source+Code+Pro)?

**Comment by etsauer** [comment]
I'm also unable to find a "monokai light" code highlighting theme... only [dark](http://raphaelddl.github.io/google-prettify-monokai-theme/)

**Comment by etsauer** [comment]
Here is a screen shot that I think shows some of the limitations of our code styling, specifically for inline code. @rdebeasi @lwrigh any ideas on how we can adjust?

![code-styling-ss](https://user-images.githubusercontent.com/4500758/43965960-3a239e2e-9c86-11e8-8af0-59ced91b0c1e.png)

**Comment by lwrigh** [comment]
I really like how slack handles styling this code snippets. Here's a screenshot of it: 
![image](https://user-images.githubusercontent.com/20227374/43970837-e1290306-9c9c-11e8-9c8d-57594bd157d6.png) 

I think having the code snippets on a black background might be too heavy in comparison to the rest of the content.

**Comment by etsauer** [comment]
@rdebeasi @JaredBurck i think this can be closed.

**Comment by JaredBurck** [comment]
agreed.
