### ISSUE TITLE
Develop styling for code blocks

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#34]

**Comment by rdebeasi** [comment]
See the [style guide](https://drive.google.com/drive/folders/17BNKus9IJYqcM05xbAa6iBXbYNlS-uTo)
![screenshot from 2018-07-13 11-11-57](https://user-images.githubusercontent.com/1299370/42699028-9c2a5748-868d-11e8-8fdf-67aa95e77d6a.png)

**Comment by etsauer** [comment]
@rdebeasi @JaredBurck we good to close this?

**Comment by JaredBurck** [comment]
agreed
