### ISSUE TITLE
Add content summaries

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#41]
I would like to see us be a bit lighter/leaner with how we present guide and article summaries.

**Comment by etsauer** [comment]
![uncontained-ss](https://user-images.githubusercontent.com/4500758/40789002-64dbbf9c-64bf-11e8-845b-dad19a323d5b.png)

**Comment by rdebeasi** [comment]
- Content work: someone needs to go through and write article summaries.

Going forward, let's write summaries when migrating.

**Comment by etsauer** [comment]
@rdebeasi starting to tackle this. Do you have a preference/thought on how we tackle the "summaries"? Seems like we have a couple of options:
1. Designate where we'd like hugo to end the summary with the `<!--more-->` tag. This means that we have to move the summary content above the `toc::[]`, or else it will be included.
2. A custom `summary` in the front-matter, which we could add rendering for in our summary layout.

**Comment by etsauer** [comment]
@rdebeasi @mwitzenm I'm going to make the call (for now) that we go with the `<!--more-->` solution, documented here: https://gohugo.io/content-management/summaries/#user-defined-manual-summary-splitting

**Comment by mwitzenm** [comment]
I started working on this and have figured out what could happen.  We could just insert the `<!--more-->` in a place where it makes sense to stop from the top of the page and let that be the summary.  I have not figured out how to create a summary that does not appear in the article yet
