### ISSUE TITLE
Support HTTPS

### ISSUE THREAD

**Issue by rdebeasi** [redhat-cop/uncontained.io#48]
https://uncontained.io/ and https://v1.uncontained.io/ fail with a certificate error. Let's get a proper certificate from Let's Encrypt and fix this issue.

> v1.uncontained.io uses an invalid security certificate.
>
>The certificate is only valid for the following names:
  *.b9ad.pro-us-east-1.openshiftapps.com, b9ad.pro-us-east-1.openshiftapps.com  
>
>Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by rdebeasi** [comment]
This is required for managed platform

**Comment by etsauer** [comment]
@JaredBurck I believe you are working on this yes?

**Comment by JaredBurck** [comment]
@JaredBurck add update for managed platform cert
