### ISSUE TITLE
Clarify how site is organized

### ISSUE THREAD

**Issue by rdebeasi** [redhat-cop/uncontained.io#54]
This is a big-picture conversation. Is the navigation easy to understand? Do readers get the difference between articles and guides?

Long-term, do we use the long-form content (guides) for everything? Do we have new types of content (e.g., field guides, deep dives, tutorials, theoretical content)? Pathways/roadmaps/collections to string together several different articles or guides into a solution?

Let's figure out how users do or don't understand this stuff, and write new issues to solve problems that come up.

**Comment by JaredBurck** [comment]
Currently defined two content types.  Simplified site designs until more content and complexity is needed. Closing as complete for now.

stale - will not fix
