### ISSUE TITLE
Support "authorship" for content

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#6]
Two components:
- Individual authors: Contributors will need to create their private profile, which will show up in the heading of each article
- Group authorships: "verified" groups which will have the option of branding themselves with a small logo

One idea that would be a nice to have would be to be able to do some kind of mapping of commiter to author so that a document over time could include metadata about the "creator" of the document, as well as people who have updated it later on.

**Comment by rdebeasi** [comment]
Hugo's built-in authorship covers the basics. New features are in #56.
