### ISSUE TITLE
Need a way to set up redirects from old article to new.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#7]
As we move content from the legacy site (v1.uncontained.io) to the new site (uncontained.io), we'll need to set up redirect links to ensure that the old articles will still point to the new stuff.

**Comment by rdebeasi** [comment]
We'll leave v1 online for a bit after v2 launches.

**Comment by rdebeasi** [comment]
Note: some content may be relevant for v2, and may need to either stay on v1 or be moved elsewhere. See #105.
