### ISSUE TITLE
Add ability to show collections of similar articles by topical groups

### ISSUE THREAD

**Issue by dstockdreher** [redhat-cop/uncontained.io#72]
Need some additional navigational tooling to be able to quickly drill down into articles that are pertaining to similar broad topic areas.  

Installation/Configuration
CI/CD - Builds
Integrations with 3rd party tooling. 
etc.

**Comment by etsauer** [comment]
ok, here are a few different ways I was thinking about categorizing content.

By Article Type:
- Implementation Guides
- Deep Dives
- Tutorials
- [something to capture docs like openshift & the org]

By Target Audience:
- Application Developers
- Operations Engineers
- Enterprise Architects
- Managers & Leadership
- Security Architects?

By Technology:
- OpenShift
- LDAP
- Jenkins
- F5

Anything else?

cc: @JaredBurck @dstockdreher @sabre1041 @rdebeasi

**Comment by etsauer** [comment]
@dstockdreher @JaredBurck @sabre1041 @rdebeasi I did some brainstorming and a little mental modeling, and came up with the proposal in #75

**Comment by etsauer** [comment]
@dstockdreher @JaredBurck @sabre1041 I'm going to migrate this content over to #75 and close this, as it is a dup
