### ISSUE TITLE
Need styling for Tables in content.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#73]
The following guide is a good example of an article with tables that needs some styling help.

https://site-uncontained--prototype.apps.d3.casl.rht-labs.com/articles/openshift-monitoring-guide/

For reference, here is the current published version of the same article:

http://v1.uncontained.io/playbooks/operationalizing/monitoring_guide.html

**Comment by lwrigh** [comment]
@etsauer Here's a quick mockup using the styling mentioned in the style guide. I ended up making the font of the code smaller (size 14px) so it doesn't overwhelm the table. What do you think? 
![table styling](https://user-images.githubusercontent.com/20227374/45646910-986be700-ba92-11e8-80d6-cb2ade63262b.png)

**Comment by etsauer** [comment]
@lwrigh perfect, thanks! @JaredBurck PR open.
