### ISSUE TITLE
Convert repo READMEs to asciidoc

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#77]

**Comment by etsauer** [comment]
@huddlesj I think we can just convert them all, except for the LICENSE.md in the theme, which I think we could just remove, since we have one in the project root already.

**Comment by JaredBurck** [comment]
@etsauer why do we want convert the READMEs from md to asciidoc?  Except for the files in the `site` directory none of these files get converted to uncontained.io site content and just are for the Github repo.

**Comment by etsauer** [comment]
This issue has been resolved by @huddlesj
