### ISSUE TITLE
Article content spilling over outside of page boundaries

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#79]
This looks to be a flexbox issue.

To reproduce:

```
npm install
npm start
```

Navigate to any article, and see that the text spills over.

![text-spilling-over](https://user-images.githubusercontent.com/4500758/46679517-2b410280-cbb5-11e8-8db9-9fb803c28089.png)

Temporarily turning off `display: flex` on a `.row` element fixes this, but that's not an option as we need rows working as-is in our layout elements.

![fixed-text-spillover](https://user-images.githubusercontent.com/4500758/46679870-d94cac80-cbb5-11e8-948b-b6fe773baa64.png)

**Comment by rdebeasi** [comment]
Looks like a combination of a couple of things:
- This article has a wide image (which may be triggering the bug)
- We're missing a column between the `<div class="row">` and the `<article>`.

```
<main class="container">
	<div class="row">
		<article>
                       <!-- content is here... -->
		</article>
	</div>
</main>
```
