### ISSUE TITLE
Admonitions are difficult to read

### ISSUE THREAD

**Issue by rdebeasi** [redhat-cop/uncontained.io#84]
Admonition text is black on dark blue. It should probably be white on dark blue. I seem to remember this being fixed previously - maybe the changes were reverted, maybe the build process didn't pick up the latest version of the styles, or maybe I'm imagining things. :)

![screenshot from 2018-10-12 17-11-18](https://user-images.githubusercontent.com/1299370/46894343-1fb63b80-ce42-11e8-8cb0-e66fa84ddea2.png)

**Comment by etsauer** [comment]
@rdebeasi we did have this in place, but then our table styling PR overwrite it. I have a fix ready to go, but it brings up another question... what do we want to do about inline code blocks in admonitions???

Currently with the fix, they will look like:
![admon-w-code](https://user-images.githubusercontent.com/4500758/46983553-a9fed980-d0a6-11e8-821d-c532d0e7816e.png)

**Comment by rdebeasi** [comment]
Oooh, good catch. I'd vote to make inline code blocks in admonitions white, like the surrounding text. Code blocks outside admonitions are black, like surrounding text, so that change seems like it would be consistent with the rest of the site

**Comment by rdebeasi** [comment]
Resolved in #91.
