### ISSUE TITLE
Fully Disconnected Openshift Installations

### ISSUE THREAD

**Issue by getarz4u15ster** [redhat-cop/uncontained.io#93]
Contribute best practice and guidance on completely disconnected OCP installs. Many of the issues addressed during an install are based on the presumption that the environment  in question is connected to the internet or even has had access to the internet which isn't always the case, and adds complexity in the way you pull images, set up registries, house the required repos, etc.

**Comment by etsauer** [comment]
@getarz4u15ster yeah, I think there's a way we could provide some callouts in the install guide where we can discuss (either in the doc, or linking out) how the approach changes when you have no internet connection.

Currently the only place we address disconnected installs is http://uncontained.io/articles/openshift-ha-installation/#_design_for_disconnected_environments, which is probably not enough. I would like to get some more specific feedback regard what is needed though, so we don't try to solve it, and still miss the mark.

Thoughts?

cc: @redhat-cop/cant-contain-this

**Comment by getarz4u15ster** [comment]
The only thing I think needs to be addressed outside of the doc link you provided is how sample apps can more easily be changed during the installation process, by the use of an inventory variable in ansible. or a new role written to address those type of scenarios. That may be an RFE type of request though and outside the scope/bounds of this venue. That's the #1 complaint i've had from customers, how to easliy change the image templates to reference internal github locations if they differ from the default so it's not ending up being done using a long sed and awk statement or rewriting the template entirely.

**Comment by getarz4u15ster** [comment]
Old, No longer relevant

**Comment by JaredBurck** [comment]
@getarz4u15ster thanks for the update. closing issue.
stale - will not fix
