### ISSUE TITLE
How might we create some cross promotion between uncontained.io and openpracticelibrary.com?

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/uncontained.io#94]
@redhat-cop/cant-contain-this

**Comment by rdebeasi** [comment]
It could be cool to add references to uncontained.io content at the bottom of [technical foundation](https://openpracticelibrary.com/#foundation-technical) articles where appropriate. I'll also bring this up in our [gitter chat](https://gitter.im/openpracticelibrary/).

**Comment by etsauer** [comment]
@rdebeasi agreed, and I think we could do the same from content in uncontained.io to openpracticelibrary. More and more I think that really uncontained.io could be where we take a lot of the technical foundations and show them in practice using specific technologies.

**Comment by mtakane** [comment]
I like the notion of having a bi-directional reference. But this would be opening the doors for other tools and technologies to be added to potentially VERY LONG lists in the Library. Not sure it is where the community wants to go, but is worth exploring and I opened up the discussion again in chat to see what people thing. Feel free to join the chat!!

**Comment by rdebeasi** [comment]
For sure - I don't think I would want to make the Library too technical, or to make uncontained.io too process-oriented. I was thinking of something really simple - like a link from something like the [CI practice](https://openpracticelibrary.com/practice/continuous-integration/) to related content in uncontained.io. I think the two sites could compliment each other.

The tricky thing here is that we do want to be agnostic of vendors and technologies. Red Hat may be organizing the project, but OpenShift isn't the only place where you can do CI, you know? :)

**Comment by etsauer** [comment]
@rdebeasi I agree that there could potentially be multiple uncontained articles that could be reference-able from any one "practice". On the uncontained.io site, what I would like to see is a small tag cloud in a sidebar that says "Practices in Action" (or something), with tags to related open practice library content. 

For example, the Install Guide and Templates Guide would have "Everything as Code" and "Containers" listed. "OpenShift and the Organization" might list "Product Ownership" and maybe one of the discovery practices

Logner term, I would like to look for opportunities where we can rework content in an uncontained.io article to relate them more closely to some of these practices.
